import type { Metadata } from 'next';

import { ThemeProvider } from '@/providers/theme-provider';
import { SheetProvider } from '@/providers/sheet-provider';
import { Header } from '@/components/header/header';
import { Footer } from '@/components/footer';
import './globals.css';

export const metadata: Metadata = {
	title: 'Simple menu with dropdown',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<>
						<SheetProvider />
						<Header />
						<main className="flex-1">{children}</main>
						<Footer />
					</>
				</ThemeProvider>
			</body>
		</html>
	);
}
